version: "3.0"
services:
  stag-api-gateway:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}
    ports:
      - 7000:7000
    environment:
      - APP_PORT=:7000
      - GRPC_USER_HOST=stag-user-service:7100
      - GRPC_STORE_HOST=stag-store-service:7200
      - JWT_SECRET=secret
      - JWT_EXPIRED_TIME=6h
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true