version: "3.0"
services:
  prod-api-gateway:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}
    ports:
      - 9000:9000
    environment:
      - APP_PORT=:9000
      - GRPC_USER_HOST=prod-user-service:9100
      - GRPC_STORE_HOST=prod-store-service:9200
      - JWT_SECRET=secret
      - JWT_EXPIRED_TIME=6h
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true