version: '3'

services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres"
      KONG_PG_PORT: 5432
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_PG_DATABASE: "kong"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
      POSTGRES_DB: "kong"

  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      DB_ADAPTER: "postgres"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_USER: "kong"
      DB_PASSWORD: "kong"
      DB_DATABASE: "konga"
    ports:
      - "1337:1337"
    depends_on:
      - kong
